// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module freq_translator_sin_or_cos_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] t_in;
input  [0:0] do_cos;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
reg    ap_block_pp0_stage0_subdone;
wire   [3:0] ref_4oPi_table_100_V_address0;
reg    ref_4oPi_table_100_V_ce0;
wire   [99:0] ref_4oPi_table_100_V_q0;
wire   [7:0] second_order_float_sin_cos_K0_V_address0;
reg    second_order_float_sin_cos_K0_V_ce0;
wire   [29:0] second_order_float_sin_cos_K0_V_q0;
wire   [7:0] second_order_float_sin_cos_K1_V_address0;
reg    second_order_float_sin_cos_K1_V_ce0;
wire   [22:0] second_order_float_sin_cos_K1_V_q0;
wire   [7:0] second_order_float_sin_cos_K2_V_address0;
reg    second_order_float_sin_cos_K2_V_ce0;
wire  signed [14:0] second_order_float_sin_cos_K2_V_q0;
reg   [0:0] do_cos_read_reg_1144;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] do_cos_read_reg_1144_pp0_iter1_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter2_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter3_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter4_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter5_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter6_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter7_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter8_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter9_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter10_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter11_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter12_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter13_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter14_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter15_reg;
reg   [0:0] do_cos_read_reg_1144_pp0_iter16_reg;
reg   [0:0] p_Result_19_reg_1151;
reg   [0:0] p_Result_19_reg_1151_pp0_iter1_reg;
reg   [0:0] p_Result_19_reg_1151_pp0_iter2_reg;
reg   [0:0] p_Result_19_reg_1151_pp0_iter3_reg;
reg   [0:0] p_Result_19_reg_1151_pp0_iter4_reg;
reg   [0:0] p_Result_19_reg_1151_pp0_iter5_reg;
reg   [0:0] p_Result_19_reg_1151_pp0_iter6_reg;
wire   [7:0] din_exp_V_fu_252_p4;
reg   [7:0] din_exp_V_reg_1157;
reg   [7:0] din_exp_V_reg_1157_pp0_iter1_reg;
reg   [7:0] din_exp_V_reg_1157_pp0_iter2_reg;
reg   [7:0] din_exp_V_reg_1157_pp0_iter3_reg;
reg   [7:0] din_exp_V_reg_1157_pp0_iter4_reg;
reg   [7:0] din_exp_V_reg_1157_pp0_iter5_reg;
reg   [7:0] din_exp_V_reg_1157_pp0_iter6_reg;
wire   [0:0] closepath_fu_266_p2;
reg   [0:0] closepath_reg_1164;
reg   [0:0] closepath_reg_1164_pp0_iter1_reg;
reg   [0:0] closepath_reg_1164_pp0_iter2_reg;
reg   [0:0] closepath_reg_1164_pp0_iter3_reg;
reg   [0:0] closepath_reg_1164_pp0_iter4_reg;
reg   [0:0] closepath_reg_1164_pp0_iter5_reg;
reg   [0:0] closepath_reg_1164_pp0_iter6_reg;
wire   [22:0] p_Result_20_fu_272_p1;
reg   [22:0] p_Result_20_reg_1171;
reg   [22:0] p_Result_20_reg_1171_pp0_iter1_reg;
wire   [3:0] trunc_ln628_fu_305_p1;
reg   [3:0] trunc_ln628_reg_1181;
wire   [0:0] and_ln1019_fu_321_p2;
reg   [0:0] and_ln1019_reg_1186;
reg   [0:0] and_ln1019_reg_1186_pp0_iter1_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter2_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter3_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter4_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter5_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter6_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter7_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter8_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter9_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter10_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter11_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter12_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter13_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter14_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter15_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter16_reg;
reg   [0:0] and_ln1019_reg_1186_pp0_iter17_reg;
reg  signed [79:0] Med_V_reg_1193;
wire   [79:0] grp_fu_357_p2;
reg   [79:0] ret_V_reg_1203;
reg   [57:0] Mx_bits_V_reg_1208;
reg   [2:0] k_V_reg_1214;
reg   [28:0] Mx_V_reg_1219;
reg   [28:0] Mx_V_reg_1219_pp0_iter8_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter9_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter10_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter11_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter12_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter13_reg;
reg   [28:0] Mx_V_reg_1219_pp0_iter14_reg;
wire  signed [7:0] Ex_V_3_fu_506_p2;
reg  signed [7:0] Ex_V_3_reg_1225;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter8_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter9_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter10_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter11_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter12_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter13_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter14_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter15_reg;
reg  signed [7:0] Ex_V_3_reg_1225_pp0_iter16_reg;
reg   [0:0] isNeg_reg_1231;
wire   [0:0] cos_basis_fu_548_p3;
reg   [0:0] cos_basis_reg_1237;
reg   [0:0] cos_basis_reg_1237_pp0_iter8_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter9_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter10_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter11_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter12_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter13_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter14_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter15_reg;
reg   [0:0] cos_basis_reg_1237_pp0_iter16_reg;
wire   [0:0] sin_basis_fu_560_p2;
reg   [0:0] sin_basis_reg_1243;
reg   [0:0] sin_basis_reg_1243_pp0_iter8_reg;
reg   [0:0] sin_basis_reg_1243_pp0_iter9_reg;
wire   [0:0] results_sign_V_3_fu_674_p2;
reg   [0:0] results_sign_V_3_reg_1248;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter8_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter9_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter10_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter11_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter12_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter13_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter14_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter15_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter16_reg;
reg   [0:0] results_sign_V_3_reg_1248_pp0_iter17_reg;
wire   [0:0] icmp_ln300_2_fu_680_p2;
reg   [0:0] icmp_ln300_2_reg_1253;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter8_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter9_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter10_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter11_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter12_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter13_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter14_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter15_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter16_reg;
reg   [0:0] icmp_ln300_2_reg_1253_pp0_iter17_reg;
wire   [21:0] B_fu_727_p1;
reg   [21:0] B_reg_1260;
reg   [21:0] B_reg_1260_pp0_iter9_reg;
reg   [21:0] B_reg_1260_pp0_iter10_reg;
reg   [21:0] B_reg_1260_pp0_iter11_reg;
reg   [6:0] tmp_1_reg_1265;
reg   [6:0] tmp_1_reg_1265_pp0_iter9_reg;
wire   [29:0] zext_ln1271_fu_751_p1;
reg   [28:0] t1_V_reg_1296;
reg   [28:0] t1_V_reg_1296_pp0_iter12_reg;
reg   [28:0] t1_V_reg_1296_pp0_iter13_reg;
reg  signed [22:0] second_order_float_sin_cos_K1_V_load_reg_1301;
reg   [21:0] rhs_1_reg_1311;
reg   [21:0] rhs_1_reg_1311_pp0_iter13_reg;
wire   [29:0] ret_V_2_fu_842_p2;
reg  signed [29:0] ret_V_2_reg_1316;
reg   [28:0] result_V_reg_1331;
reg   [15:0] tmp_3_reg_1337;
reg   [12:0] tmp_4_reg_1342;
reg   [31:0] c_2_fu_949_p3;
reg   [31:0] c_2_reg_1347;
wire   [31:0] shl_ln1454_1_fu_960_p2;
reg   [31:0] shl_ln1454_1_reg_1352;
wire   [0:0] icmp_ln321_fu_966_p2;
reg   [0:0] icmp_ln321_reg_1358;
wire   [0:0] or_ln335_fu_1015_p2;
reg   [0:0] or_ln335_reg_1363;
wire   [7:0] results_exp_V_fu_1047_p3;
reg   [7:0] results_exp_V_reg_1368;
wire   [63:0] zext_ln541_1_fu_300_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln541_fu_761_p1;
wire   [31:0] data_V_fu_240_p1;
wire   [7:0] add_ln214_fu_276_p2;
wire   [7:0] addr_fu_282_p3;
wire   [3:0] r_V_fu_290_p4;
wire   [22:0] din_sig_V_fu_262_p1;
wire   [0:0] icmp_ln300_fu_315_p2;
wire   [0:0] icmp_ln1019_fu_309_p2;
wire   [99:0] zext_ln930_fu_327_p1;
wire   [99:0] r_V_10_fu_330_p2;
wire   [23:0] p_Result_21_fu_346_p3;
wire   [23:0] grp_fu_357_p1;
wire   [7:0] Ex_V_fu_382_p2;
wire   [0:0] tmp_fu_394_p3;
wire   [0:0] xor_ln1027_fu_407_p2;
wire   [0:0] p_Result_s_fu_412_p2;
wire   [57:0] Mx_bits_V_1_fu_418_p2;
wire   [57:0] Mx_bits_V_3_fu_423_p3;
wire   [28:0] tmp_2_fu_430_p4;
wire   [29:0] p_Result_22_fu_440_p3;
reg   [29:0] p_Result_2_fu_448_p4;
wire   [30:0] p_Result_23_fu_458_p3;
wire  signed [31:0] sext_ln1198_fu_466_p1;
reg   [31:0] val_assign_fu_470_p3;
wire   [5:0] Mx_zeros_fu_478_p1;
wire   [57:0] zext_ln1454_fu_486_p1;
wire   [57:0] r_fu_490_p2;
wire   [7:0] select_ln482_fu_387_p3;
wire   [7:0] zext_ln841_fu_482_p1;
wire   [2:0] k_V_1_fu_401_p3;
wire   [0:0] tmp_s_fu_520_p10;
wire   [0:0] xor_ln271_fu_542_p2;
wire   [0:0] xor_ln25_fu_555_p2;
wire   [3:0] p_Result_29_fu_566_p3;
wire   [0:0] tmp_6_fu_573_p18;
wire   [0:0] tmp_7_fu_611_p18;
wire   [0:0] results_sign_V_2_fu_657_p2;
wire   [0:0] results_sign_V_fu_649_p3;
wire   [0:0] select_ln1019_fu_662_p3;
wire   [0:0] icmp_ln300_1_fu_669_p2;
wire  signed [8:0] sext_ln1535_fu_685_p1;
wire   [8:0] sub_ln1512_fu_688_p2;
wire   [8:0] ush_fu_694_p3;
wire   [31:0] zext_ln1488_fu_705_p1;
wire  signed [31:0] sext_ln1512_fu_701_p1;
wire   [31:0] lshr_ln1488_fu_708_p2;
wire   [31:0] shl_ln1454_fu_714_p2;
wire   [31:0] select_ln1513_fu_720_p3;
wire   [14:0] B_trunc_fu_741_p4;
wire   [7:0] p_Result_24_fu_755_p3;
wire   [29:0] B_squared_fu_768_p1;
wire  signed [29:0] grp_fu_1130_p2;
wire   [14:0] B_squared_fu_768_p4;
wire   [21:0] r_V_4_fu_801_p1;
wire   [44:0] r_V_4_fu_801_p2;
wire  signed [29:0] grp_fu_1137_p2;
wire  signed [29:0] sext_ln813_fu_826_p1;
wire  signed [29:0] sext_ln813_1_fu_829_p1;
wire   [13:0] rhs_2_fu_817_p4;
wire   [29:0] ret_V_1_fu_832_p2;
wire  signed [29:0] sext_ln1347_fu_838_p1;
wire   [28:0] Mx_V_1_fu_848_p3;
wire   [28:0] grp_fu_861_p1;
wire   [57:0] grp_fu_861_p2;
wire   [7:0] Ex_V_4_fu_897_p3;
wire   [31:0] p_Result_25_fu_907_p3;
reg   [31:0] p_Result_27_fu_921_p4;
wire   [31:0] p_Result_26_fu_914_p3;
reg   [31:0] p_Result_28_fu_939_p4;
wire   [31:0] zext_ln1488_1_fu_957_p1;
reg   [31:0] c_fu_931_p3;
wire   [31:0] add_ln319_fu_972_p2;
wire  signed [8:0] sext_ln186_fu_903_p1;
wire   [8:0] add_ln329_fu_986_p2;
wire  signed [31:0] sext_ln329_fu_992_p1;
wire   [31:0] shift_1_fu_978_p3;
wire   [31:0] newexp_fu_996_p2;
wire   [0:0] tmp_10_fu_1002_p3;
wire   [0:0] icmp_ln1653_fu_1010_p2;
wire   [7:0] trunc_ln214_fu_1021_p1;
wire   [7:0] select_ln288_fu_1033_p3;
wire   [7:0] out_exp_V_fu_1025_p3;
wire   [7:0] select_ln1019_1_fu_1040_p3;
wire   [27:0] r_V_11_fu_1054_p1;
wire   [31:0] zext_ln1488_2_fu_1057_p1;
wire   [31:0] shl_ln1454_2_fu_1061_p2;
wire   [22:0] tmp_8_fu_1066_p4;
wire   [22:0] tmp_9_fu_1076_p4;
wire   [22:0] select_ln321_fu_1085_p3;
wire   [0:0] or_ln300_fu_1106_p2;
wire   [22:0] select_ln300_1_fu_1099_p3;
wire   [22:0] significand_fu_1092_p3;
wire   [22:0] results_sig_V_fu_1110_p3;
wire   [31:0] p_Result_30_fu_1118_p4;
wire   [14:0] grp_fu_1130_p0;
wire   [14:0] grp_fu_1130_p1;
wire   [14:0] grp_fu_1137_p0;
reg    grp_fu_357_ce;
reg    grp_fu_861_ce;
reg    grp_fu_1130_ce;
reg    grp_fu_1137_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to17;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [29:0] grp_fu_1137_p00;
wire   [79:0] grp_fu_357_p10;
wire   [57:0] grp_fu_861_p10;
wire   [44:0] r_V_4_fu_801_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
end

freq_translator_sin_or_cos_float_s_ref_4oPi_table_100_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_V_address0),
    .ce0(ref_4oPi_table_100_V_ce0),
    .q0(ref_4oPi_table_100_V_q0)
);

freq_translator_sin_or_cos_float_s_second_order_float_sin_cos_K0_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_V_address0),
    .ce0(second_order_float_sin_cos_K0_V_ce0),
    .q0(second_order_float_sin_cos_K0_V_q0)
);

freq_translator_sin_or_cos_float_s_second_order_float_sin_cos_K1_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_V_address0),
    .ce0(second_order_float_sin_cos_K1_V_ce0),
    .q0(second_order_float_sin_cos_K1_V_q0)
);

freq_translator_sin_or_cos_float_s_second_order_float_sin_cos_K2_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_V_address0),
    .ce0(second_order_float_sin_cos_K2_V_ce0),
    .q0(second_order_float_sin_cos_K2_V_q0)
);

freq_translator_mul_80s_24ns_80_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Med_V_reg_1193),
    .din1(grp_fu_357_p1),
    .ce(grp_fu_357_ce),
    .dout(grp_fu_357_p2)
);

freq_translator_mux_83_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_1_U2(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(k_V_1_fu_401_p3),
    .dout(tmp_s_fu_520_p10)
);

freq_translator_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
mux_164_1_1_1_U3(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_29_fu_566_p3),
    .dout(tmp_6_fu_573_p18)
);

freq_translator_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
mux_164_1_1_1_U4(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_29_fu_566_p3),
    .dout(tmp_7_fu_611_p18)
);

freq_translator_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U5(
    .din0(second_order_float_sin_cos_K1_V_load_reg_1301),
    .din1(r_V_4_fu_801_p1),
    .dout(r_V_4_fu_801_p2)
);

freq_translator_mul_30s_29ns_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_2_reg_1316),
    .din1(grp_fu_861_p1),
    .ce(grp_fu_861_ce),
    .dout(grp_fu_861_p2)
);

freq_translator_mul_mul_15ns_15ns_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_mul_15ns_15ns_30_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1130_p0),
    .din1(grp_fu_1130_p1),
    .ce(grp_fu_1130_ce),
    .dout(grp_fu_1130_p2)
);

freq_translator_mul_mul_15ns_15s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_mul_15ns_15s_30_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1137_p0),
    .din1(second_order_float_sin_cos_K2_V_q0),
    .ce(grp_fu_1137_ce),
    .dout(grp_fu_1137_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_reg_1260 <= B_fu_727_p1;
        B_reg_1260_pp0_iter10_reg <= B_reg_1260_pp0_iter9_reg;
        B_reg_1260_pp0_iter11_reg <= B_reg_1260_pp0_iter10_reg;
        B_reg_1260_pp0_iter9_reg <= B_reg_1260;
        Ex_V_3_reg_1225 <= Ex_V_3_fu_506_p2;
        Ex_V_3_reg_1225_pp0_iter10_reg <= Ex_V_3_reg_1225_pp0_iter9_reg;
        Ex_V_3_reg_1225_pp0_iter11_reg <= Ex_V_3_reg_1225_pp0_iter10_reg;
        Ex_V_3_reg_1225_pp0_iter12_reg <= Ex_V_3_reg_1225_pp0_iter11_reg;
        Ex_V_3_reg_1225_pp0_iter13_reg <= Ex_V_3_reg_1225_pp0_iter12_reg;
        Ex_V_3_reg_1225_pp0_iter14_reg <= Ex_V_3_reg_1225_pp0_iter13_reg;
        Ex_V_3_reg_1225_pp0_iter15_reg <= Ex_V_3_reg_1225_pp0_iter14_reg;
        Ex_V_3_reg_1225_pp0_iter16_reg <= Ex_V_3_reg_1225_pp0_iter15_reg;
        Ex_V_3_reg_1225_pp0_iter8_reg <= Ex_V_3_reg_1225;
        Ex_V_3_reg_1225_pp0_iter9_reg <= Ex_V_3_reg_1225_pp0_iter8_reg;
        Mx_V_reg_1219 <= {{r_fu_490_p2[57:29]}};
        Mx_V_reg_1219_pp0_iter10_reg <= Mx_V_reg_1219_pp0_iter9_reg;
        Mx_V_reg_1219_pp0_iter11_reg <= Mx_V_reg_1219_pp0_iter10_reg;
        Mx_V_reg_1219_pp0_iter12_reg <= Mx_V_reg_1219_pp0_iter11_reg;
        Mx_V_reg_1219_pp0_iter13_reg <= Mx_V_reg_1219_pp0_iter12_reg;
        Mx_V_reg_1219_pp0_iter14_reg <= Mx_V_reg_1219_pp0_iter13_reg;
        Mx_V_reg_1219_pp0_iter8_reg <= Mx_V_reg_1219;
        Mx_V_reg_1219_pp0_iter9_reg <= Mx_V_reg_1219_pp0_iter8_reg;
        Mx_bits_V_reg_1208 <= {{grp_fu_357_p2[76:19]}};
        and_ln1019_reg_1186_pp0_iter10_reg <= and_ln1019_reg_1186_pp0_iter9_reg;
        and_ln1019_reg_1186_pp0_iter11_reg <= and_ln1019_reg_1186_pp0_iter10_reg;
        and_ln1019_reg_1186_pp0_iter12_reg <= and_ln1019_reg_1186_pp0_iter11_reg;
        and_ln1019_reg_1186_pp0_iter13_reg <= and_ln1019_reg_1186_pp0_iter12_reg;
        and_ln1019_reg_1186_pp0_iter14_reg <= and_ln1019_reg_1186_pp0_iter13_reg;
        and_ln1019_reg_1186_pp0_iter15_reg <= and_ln1019_reg_1186_pp0_iter14_reg;
        and_ln1019_reg_1186_pp0_iter16_reg <= and_ln1019_reg_1186_pp0_iter15_reg;
        and_ln1019_reg_1186_pp0_iter17_reg <= and_ln1019_reg_1186_pp0_iter16_reg;
        and_ln1019_reg_1186_pp0_iter2_reg <= and_ln1019_reg_1186_pp0_iter1_reg;
        and_ln1019_reg_1186_pp0_iter3_reg <= and_ln1019_reg_1186_pp0_iter2_reg;
        and_ln1019_reg_1186_pp0_iter4_reg <= and_ln1019_reg_1186_pp0_iter3_reg;
        and_ln1019_reg_1186_pp0_iter5_reg <= and_ln1019_reg_1186_pp0_iter4_reg;
        and_ln1019_reg_1186_pp0_iter6_reg <= and_ln1019_reg_1186_pp0_iter5_reg;
        and_ln1019_reg_1186_pp0_iter7_reg <= and_ln1019_reg_1186_pp0_iter6_reg;
        and_ln1019_reg_1186_pp0_iter8_reg <= and_ln1019_reg_1186_pp0_iter7_reg;
        and_ln1019_reg_1186_pp0_iter9_reg <= and_ln1019_reg_1186_pp0_iter8_reg;
        c_2_reg_1347 <= c_2_fu_949_p3;
        closepath_reg_1164_pp0_iter2_reg <= closepath_reg_1164_pp0_iter1_reg;
        closepath_reg_1164_pp0_iter3_reg <= closepath_reg_1164_pp0_iter2_reg;
        closepath_reg_1164_pp0_iter4_reg <= closepath_reg_1164_pp0_iter3_reg;
        closepath_reg_1164_pp0_iter5_reg <= closepath_reg_1164_pp0_iter4_reg;
        closepath_reg_1164_pp0_iter6_reg <= closepath_reg_1164_pp0_iter5_reg;
        cos_basis_reg_1237 <= cos_basis_fu_548_p3;
        cos_basis_reg_1237_pp0_iter10_reg <= cos_basis_reg_1237_pp0_iter9_reg;
        cos_basis_reg_1237_pp0_iter11_reg <= cos_basis_reg_1237_pp0_iter10_reg;
        cos_basis_reg_1237_pp0_iter12_reg <= cos_basis_reg_1237_pp0_iter11_reg;
        cos_basis_reg_1237_pp0_iter13_reg <= cos_basis_reg_1237_pp0_iter12_reg;
        cos_basis_reg_1237_pp0_iter14_reg <= cos_basis_reg_1237_pp0_iter13_reg;
        cos_basis_reg_1237_pp0_iter15_reg <= cos_basis_reg_1237_pp0_iter14_reg;
        cos_basis_reg_1237_pp0_iter16_reg <= cos_basis_reg_1237_pp0_iter15_reg;
        cos_basis_reg_1237_pp0_iter8_reg <= cos_basis_reg_1237;
        cos_basis_reg_1237_pp0_iter9_reg <= cos_basis_reg_1237_pp0_iter8_reg;
        din_exp_V_reg_1157_pp0_iter2_reg <= din_exp_V_reg_1157_pp0_iter1_reg;
        din_exp_V_reg_1157_pp0_iter3_reg <= din_exp_V_reg_1157_pp0_iter2_reg;
        din_exp_V_reg_1157_pp0_iter4_reg <= din_exp_V_reg_1157_pp0_iter3_reg;
        din_exp_V_reg_1157_pp0_iter5_reg <= din_exp_V_reg_1157_pp0_iter4_reg;
        din_exp_V_reg_1157_pp0_iter6_reg <= din_exp_V_reg_1157_pp0_iter5_reg;
        do_cos_read_reg_1144_pp0_iter10_reg <= do_cos_read_reg_1144_pp0_iter9_reg;
        do_cos_read_reg_1144_pp0_iter11_reg <= do_cos_read_reg_1144_pp0_iter10_reg;
        do_cos_read_reg_1144_pp0_iter12_reg <= do_cos_read_reg_1144_pp0_iter11_reg;
        do_cos_read_reg_1144_pp0_iter13_reg <= do_cos_read_reg_1144_pp0_iter12_reg;
        do_cos_read_reg_1144_pp0_iter14_reg <= do_cos_read_reg_1144_pp0_iter13_reg;
        do_cos_read_reg_1144_pp0_iter15_reg <= do_cos_read_reg_1144_pp0_iter14_reg;
        do_cos_read_reg_1144_pp0_iter16_reg <= do_cos_read_reg_1144_pp0_iter15_reg;
        do_cos_read_reg_1144_pp0_iter2_reg <= do_cos_read_reg_1144_pp0_iter1_reg;
        do_cos_read_reg_1144_pp0_iter3_reg <= do_cos_read_reg_1144_pp0_iter2_reg;
        do_cos_read_reg_1144_pp0_iter4_reg <= do_cos_read_reg_1144_pp0_iter3_reg;
        do_cos_read_reg_1144_pp0_iter5_reg <= do_cos_read_reg_1144_pp0_iter4_reg;
        do_cos_read_reg_1144_pp0_iter6_reg <= do_cos_read_reg_1144_pp0_iter5_reg;
        do_cos_read_reg_1144_pp0_iter7_reg <= do_cos_read_reg_1144_pp0_iter6_reg;
        do_cos_read_reg_1144_pp0_iter8_reg <= do_cos_read_reg_1144_pp0_iter7_reg;
        do_cos_read_reg_1144_pp0_iter9_reg <= do_cos_read_reg_1144_pp0_iter8_reg;
        icmp_ln300_2_reg_1253 <= icmp_ln300_2_fu_680_p2;
        icmp_ln300_2_reg_1253_pp0_iter10_reg <= icmp_ln300_2_reg_1253_pp0_iter9_reg;
        icmp_ln300_2_reg_1253_pp0_iter11_reg <= icmp_ln300_2_reg_1253_pp0_iter10_reg;
        icmp_ln300_2_reg_1253_pp0_iter12_reg <= icmp_ln300_2_reg_1253_pp0_iter11_reg;
        icmp_ln300_2_reg_1253_pp0_iter13_reg <= icmp_ln300_2_reg_1253_pp0_iter12_reg;
        icmp_ln300_2_reg_1253_pp0_iter14_reg <= icmp_ln300_2_reg_1253_pp0_iter13_reg;
        icmp_ln300_2_reg_1253_pp0_iter15_reg <= icmp_ln300_2_reg_1253_pp0_iter14_reg;
        icmp_ln300_2_reg_1253_pp0_iter16_reg <= icmp_ln300_2_reg_1253_pp0_iter15_reg;
        icmp_ln300_2_reg_1253_pp0_iter17_reg <= icmp_ln300_2_reg_1253_pp0_iter16_reg;
        icmp_ln300_2_reg_1253_pp0_iter8_reg <= icmp_ln300_2_reg_1253;
        icmp_ln300_2_reg_1253_pp0_iter9_reg <= icmp_ln300_2_reg_1253_pp0_iter8_reg;
        icmp_ln321_reg_1358 <= icmp_ln321_fu_966_p2;
        isNeg_reg_1231 <= Ex_V_3_fu_506_p2[32'd7];
        or_ln335_reg_1363 <= or_ln335_fu_1015_p2;
        p_Result_19_reg_1151_pp0_iter2_reg <= p_Result_19_reg_1151_pp0_iter1_reg;
        p_Result_19_reg_1151_pp0_iter3_reg <= p_Result_19_reg_1151_pp0_iter2_reg;
        p_Result_19_reg_1151_pp0_iter4_reg <= p_Result_19_reg_1151_pp0_iter3_reg;
        p_Result_19_reg_1151_pp0_iter5_reg <= p_Result_19_reg_1151_pp0_iter4_reg;
        p_Result_19_reg_1151_pp0_iter6_reg <= p_Result_19_reg_1151_pp0_iter5_reg;
        result_V_reg_1331 <= {{grp_fu_861_p2[57:29]}};
        results_exp_V_reg_1368 <= results_exp_V_fu_1047_p3;
        results_sign_V_3_reg_1248 <= results_sign_V_3_fu_674_p2;
        results_sign_V_3_reg_1248_pp0_iter10_reg <= results_sign_V_3_reg_1248_pp0_iter9_reg;
        results_sign_V_3_reg_1248_pp0_iter11_reg <= results_sign_V_3_reg_1248_pp0_iter10_reg;
        results_sign_V_3_reg_1248_pp0_iter12_reg <= results_sign_V_3_reg_1248_pp0_iter11_reg;
        results_sign_V_3_reg_1248_pp0_iter13_reg <= results_sign_V_3_reg_1248_pp0_iter12_reg;
        results_sign_V_3_reg_1248_pp0_iter14_reg <= results_sign_V_3_reg_1248_pp0_iter13_reg;
        results_sign_V_3_reg_1248_pp0_iter15_reg <= results_sign_V_3_reg_1248_pp0_iter14_reg;
        results_sign_V_3_reg_1248_pp0_iter16_reg <= results_sign_V_3_reg_1248_pp0_iter15_reg;
        results_sign_V_3_reg_1248_pp0_iter17_reg <= results_sign_V_3_reg_1248_pp0_iter16_reg;
        results_sign_V_3_reg_1248_pp0_iter8_reg <= results_sign_V_3_reg_1248;
        results_sign_V_3_reg_1248_pp0_iter9_reg <= results_sign_V_3_reg_1248_pp0_iter8_reg;
        ret_V_2_reg_1316 <= ret_V_2_fu_842_p2;
        ret_V_reg_1203 <= grp_fu_357_p2;
        rhs_1_reg_1311 <= {{r_V_4_fu_801_p2[44:23]}};
        rhs_1_reg_1311_pp0_iter13_reg <= rhs_1_reg_1311;
        second_order_float_sin_cos_K1_V_load_reg_1301 <= second_order_float_sin_cos_K1_V_q0;
        shl_ln1454_1_reg_1352 <= shl_ln1454_1_fu_960_p2;
        sin_basis_reg_1243 <= sin_basis_fu_560_p2;
        sin_basis_reg_1243_pp0_iter8_reg <= sin_basis_reg_1243;
        sin_basis_reg_1243_pp0_iter9_reg <= sin_basis_reg_1243_pp0_iter8_reg;
        t1_V_reg_1296 <= {{second_order_float_sin_cos_K0_V_q0[29:1]}};
        t1_V_reg_1296_pp0_iter12_reg <= t1_V_reg_1296;
        t1_V_reg_1296_pp0_iter13_reg <= t1_V_reg_1296_pp0_iter12_reg;
        tmp_1_reg_1265 <= {{select_ln1513_fu_720_p3[28:22]}};
        tmp_1_reg_1265_pp0_iter9_reg <= tmp_1_reg_1265;
        tmp_3_reg_1337 <= {{grp_fu_861_p2[57:42]}};
        tmp_4_reg_1342 <= {{grp_fu_861_p2[41:29]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Med_V_reg_1193 <= {{r_V_10_fu_330_p2[99:20]}};
        and_ln1019_reg_1186 <= and_ln1019_fu_321_p2;
        and_ln1019_reg_1186_pp0_iter1_reg <= and_ln1019_reg_1186;
        closepath_reg_1164 <= closepath_fu_266_p2;
        closepath_reg_1164_pp0_iter1_reg <= closepath_reg_1164;
        din_exp_V_reg_1157 <= {{data_V_fu_240_p1[30:23]}};
        din_exp_V_reg_1157_pp0_iter1_reg <= din_exp_V_reg_1157;
        do_cos_read_reg_1144 <= do_cos;
        do_cos_read_reg_1144_pp0_iter1_reg <= do_cos_read_reg_1144;
        p_Result_19_reg_1151 <= data_V_fu_240_p1[32'd31];
        p_Result_19_reg_1151_pp0_iter1_reg <= p_Result_19_reg_1151;
        p_Result_20_reg_1171 <= p_Result_20_fu_272_p1;
        p_Result_20_reg_1171_pp0_iter1_reg <= p_Result_20_reg_1171;
        trunc_ln628_reg_1181 <= trunc_ln628_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (closepath_reg_1164_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_V_reg_1214 <= {{grp_fu_357_p2[79:77]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to17 = 1'b1;
    end else begin
        ap_idle_pp0_0to17 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1130_ce = 1'b1;
    end else begin
        grp_fu_1130_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1137_ce = 1'b1;
    end else begin
        grp_fu_1137_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_357_ce = 1'b1;
    end else begin
        grp_fu_357_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_861_ce = 1'b1;
    end else begin
        grp_fu_861_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ref_4oPi_table_100_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_100_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        second_order_float_sin_cos_K0_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        second_order_float_sin_cos_K1_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        second_order_float_sin_cos_K2_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_727_p1 = select_ln1513_fu_720_p3[21:0];

assign B_squared_fu_768_p1 = grp_fu_1130_p2;

assign B_squared_fu_768_p4 = {{B_squared_fu_768_p1[29:15]}};

assign B_trunc_fu_741_p4 = {{select_ln1513_fu_720_p3[21:7]}};

assign Ex_V_3_fu_506_p2 = (select_ln482_fu_387_p3 - zext_ln841_fu_482_p1);

assign Ex_V_4_fu_897_p3 = ((cos_basis_reg_1237_pp0_iter16_reg[0:0] == 1'b1) ? 8'd0 : Ex_V_3_reg_1225_pp0_iter16_reg);

assign Ex_V_fu_382_p2 = ($signed(din_exp_V_reg_1157_pp0_iter6_reg) + $signed(8'd131));

assign Mx_V_1_fu_848_p3 = ((cos_basis_reg_1237_pp0_iter14_reg[0:0] == 1'b1) ? 29'd536870911 : Mx_V_reg_1219_pp0_iter14_reg);

assign Mx_bits_V_1_fu_418_p2 = (58'd0 - Mx_bits_V_reg_1208);

assign Mx_bits_V_3_fu_423_p3 = ((p_Result_s_fu_412_p2[0:0] == 1'b1) ? Mx_bits_V_1_fu_418_p2 : Mx_bits_V_reg_1208);

assign Mx_zeros_fu_478_p1 = val_assign_fu_470_p3[5:0];

assign add_ln214_fu_276_p2 = ($signed(din_exp_V_fu_252_p4) + $signed(8'd194));

assign add_ln319_fu_972_p2 = (c_2_fu_949_p3 + 32'd16);

assign add_ln329_fu_986_p2 = ($signed(sext_ln186_fu_903_p1) + $signed(9'd127));

assign addr_fu_282_p3 = ((closepath_fu_266_p2[0:0] == 1'b1) ? 8'd63 : add_ln214_fu_276_p2);

assign and_ln1019_fu_321_p2 = (icmp_ln300_fu_315_p2 & icmp_ln1019_fu_309_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = p_Result_30_fu_1118_p4;


always @ (p_Result_28_fu_939_p4) begin
    if (p_Result_28_fu_939_p4[0] == 1'b1) begin
        c_2_fu_949_p3 = 32'd0;
    end else if (p_Result_28_fu_939_p4[1] == 1'b1) begin
        c_2_fu_949_p3 = 32'd1;
    end else if (p_Result_28_fu_939_p4[2] == 1'b1) begin
        c_2_fu_949_p3 = 32'd2;
    end else if (p_Result_28_fu_939_p4[3] == 1'b1) begin
        c_2_fu_949_p3 = 32'd3;
    end else if (p_Result_28_fu_939_p4[4] == 1'b1) begin
        c_2_fu_949_p3 = 32'd4;
    end else if (p_Result_28_fu_939_p4[5] == 1'b1) begin
        c_2_fu_949_p3 = 32'd5;
    end else if (p_Result_28_fu_939_p4[6] == 1'b1) begin
        c_2_fu_949_p3 = 32'd6;
    end else if (p_Result_28_fu_939_p4[7] == 1'b1) begin
        c_2_fu_949_p3 = 32'd7;
    end else if (p_Result_28_fu_939_p4[8] == 1'b1) begin
        c_2_fu_949_p3 = 32'd8;
    end else if (p_Result_28_fu_939_p4[9] == 1'b1) begin
        c_2_fu_949_p3 = 32'd9;
    end else if (p_Result_28_fu_939_p4[10] == 1'b1) begin
        c_2_fu_949_p3 = 32'd10;
    end else if (p_Result_28_fu_939_p4[11] == 1'b1) begin
        c_2_fu_949_p3 = 32'd11;
    end else if (p_Result_28_fu_939_p4[12] == 1'b1) begin
        c_2_fu_949_p3 = 32'd12;
    end else if (p_Result_28_fu_939_p4[13] == 1'b1) begin
        c_2_fu_949_p3 = 32'd13;
    end else if (p_Result_28_fu_939_p4[14] == 1'b1) begin
        c_2_fu_949_p3 = 32'd14;
    end else if (p_Result_28_fu_939_p4[15] == 1'b1) begin
        c_2_fu_949_p3 = 32'd15;
    end else if (p_Result_28_fu_939_p4[16] == 1'b1) begin
        c_2_fu_949_p3 = 32'd16;
    end else if (p_Result_28_fu_939_p4[17] == 1'b1) begin
        c_2_fu_949_p3 = 32'd17;
    end else if (p_Result_28_fu_939_p4[18] == 1'b1) begin
        c_2_fu_949_p3 = 32'd18;
    end else if (p_Result_28_fu_939_p4[19] == 1'b1) begin
        c_2_fu_949_p3 = 32'd19;
    end else if (p_Result_28_fu_939_p4[20] == 1'b1) begin
        c_2_fu_949_p3 = 32'd20;
    end else if (p_Result_28_fu_939_p4[21] == 1'b1) begin
        c_2_fu_949_p3 = 32'd21;
    end else if (p_Result_28_fu_939_p4[22] == 1'b1) begin
        c_2_fu_949_p3 = 32'd22;
    end else if (p_Result_28_fu_939_p4[23] == 1'b1) begin
        c_2_fu_949_p3 = 32'd23;
    end else if (p_Result_28_fu_939_p4[24] == 1'b1) begin
        c_2_fu_949_p3 = 32'd24;
    end else if (p_Result_28_fu_939_p4[25] == 1'b1) begin
        c_2_fu_949_p3 = 32'd25;
    end else if (p_Result_28_fu_939_p4[26] == 1'b1) begin
        c_2_fu_949_p3 = 32'd26;
    end else if (p_Result_28_fu_939_p4[27] == 1'b1) begin
        c_2_fu_949_p3 = 32'd27;
    end else if (p_Result_28_fu_939_p4[28] == 1'b1) begin
        c_2_fu_949_p3 = 32'd28;
    end else if (p_Result_28_fu_939_p4[29] == 1'b1) begin
        c_2_fu_949_p3 = 32'd29;
    end else if (p_Result_28_fu_939_p4[30] == 1'b1) begin
        c_2_fu_949_p3 = 32'd30;
    end else if (p_Result_28_fu_939_p4[31] == 1'b1) begin
        c_2_fu_949_p3 = 32'd31;
    end else begin
        c_2_fu_949_p3 = 32'd32;
    end
end


always @ (p_Result_27_fu_921_p4) begin
    if (p_Result_27_fu_921_p4[0] == 1'b1) begin
        c_fu_931_p3 = 32'd0;
    end else if (p_Result_27_fu_921_p4[1] == 1'b1) begin
        c_fu_931_p3 = 32'd1;
    end else if (p_Result_27_fu_921_p4[2] == 1'b1) begin
        c_fu_931_p3 = 32'd2;
    end else if (p_Result_27_fu_921_p4[3] == 1'b1) begin
        c_fu_931_p3 = 32'd3;
    end else if (p_Result_27_fu_921_p4[4] == 1'b1) begin
        c_fu_931_p3 = 32'd4;
    end else if (p_Result_27_fu_921_p4[5] == 1'b1) begin
        c_fu_931_p3 = 32'd5;
    end else if (p_Result_27_fu_921_p4[6] == 1'b1) begin
        c_fu_931_p3 = 32'd6;
    end else if (p_Result_27_fu_921_p4[7] == 1'b1) begin
        c_fu_931_p3 = 32'd7;
    end else if (p_Result_27_fu_921_p4[8] == 1'b1) begin
        c_fu_931_p3 = 32'd8;
    end else if (p_Result_27_fu_921_p4[9] == 1'b1) begin
        c_fu_931_p3 = 32'd9;
    end else if (p_Result_27_fu_921_p4[10] == 1'b1) begin
        c_fu_931_p3 = 32'd10;
    end else if (p_Result_27_fu_921_p4[11] == 1'b1) begin
        c_fu_931_p3 = 32'd11;
    end else if (p_Result_27_fu_921_p4[12] == 1'b1) begin
        c_fu_931_p3 = 32'd12;
    end else if (p_Result_27_fu_921_p4[13] == 1'b1) begin
        c_fu_931_p3 = 32'd13;
    end else if (p_Result_27_fu_921_p4[14] == 1'b1) begin
        c_fu_931_p3 = 32'd14;
    end else if (p_Result_27_fu_921_p4[15] == 1'b1) begin
        c_fu_931_p3 = 32'd15;
    end else if (p_Result_27_fu_921_p4[16] == 1'b1) begin
        c_fu_931_p3 = 32'd16;
    end else if (p_Result_27_fu_921_p4[17] == 1'b1) begin
        c_fu_931_p3 = 32'd17;
    end else if (p_Result_27_fu_921_p4[18] == 1'b1) begin
        c_fu_931_p3 = 32'd18;
    end else if (p_Result_27_fu_921_p4[19] == 1'b1) begin
        c_fu_931_p3 = 32'd19;
    end else if (p_Result_27_fu_921_p4[20] == 1'b1) begin
        c_fu_931_p3 = 32'd20;
    end else if (p_Result_27_fu_921_p4[21] == 1'b1) begin
        c_fu_931_p3 = 32'd21;
    end else if (p_Result_27_fu_921_p4[22] == 1'b1) begin
        c_fu_931_p3 = 32'd22;
    end else if (p_Result_27_fu_921_p4[23] == 1'b1) begin
        c_fu_931_p3 = 32'd23;
    end else if (p_Result_27_fu_921_p4[24] == 1'b1) begin
        c_fu_931_p3 = 32'd24;
    end else if (p_Result_27_fu_921_p4[25] == 1'b1) begin
        c_fu_931_p3 = 32'd25;
    end else if (p_Result_27_fu_921_p4[26] == 1'b1) begin
        c_fu_931_p3 = 32'd26;
    end else if (p_Result_27_fu_921_p4[27] == 1'b1) begin
        c_fu_931_p3 = 32'd27;
    end else if (p_Result_27_fu_921_p4[28] == 1'b1) begin
        c_fu_931_p3 = 32'd28;
    end else if (p_Result_27_fu_921_p4[29] == 1'b1) begin
        c_fu_931_p3 = 32'd29;
    end else if (p_Result_27_fu_921_p4[30] == 1'b1) begin
        c_fu_931_p3 = 32'd30;
    end else if (p_Result_27_fu_921_p4[31] == 1'b1) begin
        c_fu_931_p3 = 32'd31;
    end else begin
        c_fu_931_p3 = 32'd32;
    end
end

assign closepath_fu_266_p2 = ((din_exp_V_fu_252_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cos_basis_fu_548_p3 = ((do_cos_read_reg_1144_pp0_iter6_reg[0:0] == 1'b1) ? xor_ln271_fu_542_p2 : tmp_s_fu_520_p10);

assign data_V_fu_240_p1 = t_in;

assign din_exp_V_fu_252_p4 = {{data_V_fu_240_p1[30:23]}};

assign din_sig_V_fu_262_p1 = data_V_fu_240_p1[22:0];

assign grp_fu_1130_p0 = zext_ln1271_fu_751_p1;

assign grp_fu_1130_p1 = zext_ln1271_fu_751_p1;

assign grp_fu_1137_p0 = grp_fu_1137_p00;

assign grp_fu_1137_p00 = B_squared_fu_768_p4;

assign grp_fu_357_p1 = grp_fu_357_p10;

assign grp_fu_357_p10 = p_Result_21_fu_346_p3;

assign grp_fu_861_p1 = grp_fu_861_p10;

assign grp_fu_861_p10 = Mx_V_1_fu_848_p3;

assign icmp_ln1019_fu_309_p2 = ((din_sig_V_fu_262_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1653_fu_1010_p2 = ((result_V_reg_1331 == 29'd0) ? 1'b1 : 1'b0);

assign icmp_ln300_1_fu_669_p2 = ((din_exp_V_reg_1157_pp0_iter6_reg != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln300_2_fu_680_p2 = ((din_exp_V_reg_1157_pp0_iter6_reg == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln300_fu_315_p2 = ((din_exp_V_fu_252_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_966_p2 = ((c_fu_931_p3 == 32'd16) ? 1'b1 : 1'b0);

assign k_V_1_fu_401_p3 = ((closepath_reg_1164_pp0_iter6_reg[0:0] == 1'b1) ? 3'd0 : k_V_reg_1214);

assign lshr_ln1488_fu_708_p2 = zext_ln1488_fu_705_p1 >> sext_ln1512_fu_701_p1;

assign newexp_fu_996_p2 = ($signed(sext_ln329_fu_992_p1) - $signed(shift_1_fu_978_p3));

assign or_ln300_fu_1106_p2 = (icmp_ln300_2_reg_1253_pp0_iter17_reg | and_ln1019_reg_1186_pp0_iter17_reg);

assign or_ln335_fu_1015_p2 = (tmp_10_fu_1002_p3 | icmp_ln1653_fu_1010_p2);

assign out_exp_V_fu_1025_p3 = ((or_ln335_fu_1015_p2[0:0] == 1'b1) ? 8'd0 : trunc_ln214_fu_1021_p1);

assign p_Result_20_fu_272_p1 = data_V_fu_240_p1[22:0];

assign p_Result_21_fu_346_p3 = {{1'd1}, {p_Result_20_reg_1171_pp0_iter1_reg}};

assign p_Result_22_fu_440_p3 = {{tmp_2_fu_430_p4}, {1'd1}};

assign p_Result_23_fu_458_p3 = {{1'd1}, {p_Result_2_fu_448_p4}};

assign p_Result_24_fu_755_p3 = {{sin_basis_reg_1243_pp0_iter9_reg}, {tmp_1_reg_1265_pp0_iter9_reg}};

assign p_Result_25_fu_907_p3 = {{tmp_3_reg_1337}, {16'd32768}};

assign p_Result_26_fu_914_p3 = {{tmp_4_reg_1342}, {19'd262144}};

integer ap_tvar_int_0;

always @ (p_Result_25_fu_907_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_27_fu_921_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_27_fu_921_p4[ap_tvar_int_0] = p_Result_25_fu_907_p3[31 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (p_Result_26_fu_914_p3) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            p_Result_28_fu_939_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_28_fu_939_p4[ap_tvar_int_1] = p_Result_26_fu_914_p3[31 - ap_tvar_int_1];
        end
    end
end

assign p_Result_29_fu_566_p3 = {{p_Result_19_reg_1151_pp0_iter6_reg}, {k_V_1_fu_401_p3}};

integer ap_tvar_int_2;

always @ (p_Result_22_fu_440_p3) begin
    for (ap_tvar_int_2 = 30 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 29 - 0) begin
            p_Result_2_fu_448_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_2_fu_448_p4[ap_tvar_int_2] = p_Result_22_fu_440_p3[29 - ap_tvar_int_2];
        end
    end
end

assign p_Result_30_fu_1118_p4 = {{{results_sign_V_3_reg_1248_pp0_iter17_reg}, {results_exp_V_reg_1368}}, {results_sig_V_fu_1110_p3}};

assign p_Result_s_fu_412_p2 = (xor_ln1027_fu_407_p2 & tmp_fu_394_p3);

assign r_V_10_fu_330_p2 = ref_4oPi_table_100_V_q0 << zext_ln930_fu_327_p1;

assign r_V_11_fu_1054_p1 = shl_ln1454_1_reg_1352[27:0];

assign r_V_4_fu_801_p1 = r_V_4_fu_801_p10;

assign r_V_4_fu_801_p10 = B_reg_1260_pp0_iter11_reg;

assign r_V_fu_290_p4 = {{addr_fu_282_p3[7:4]}};

assign r_fu_490_p2 = Mx_bits_V_3_fu_423_p3 << zext_ln1454_fu_486_p1;

assign ref_4oPi_table_100_V_address0 = zext_ln541_1_fu_300_p1;

assign results_exp_V_fu_1047_p3 = ((icmp_ln300_2_reg_1253_pp0_iter16_reg[0:0] == 1'b1) ? 8'd255 : select_ln1019_1_fu_1040_p3);

assign results_sig_V_fu_1110_p3 = ((or_ln300_fu_1106_p2[0:0] == 1'b1) ? select_ln300_1_fu_1099_p3 : significand_fu_1092_p3);

assign results_sign_V_2_fu_657_p2 = (xor_ln25_fu_555_p2 & p_Result_19_reg_1151_pp0_iter6_reg);

assign results_sign_V_3_fu_674_p2 = (select_ln1019_fu_662_p3 & icmp_ln300_1_fu_669_p2);

assign results_sign_V_fu_649_p3 = ((cos_basis_fu_548_p3[0:0] == 1'b1) ? tmp_6_fu_573_p18 : tmp_7_fu_611_p18);

assign ret_V_1_fu_832_p2 = ($signed(sext_ln813_fu_826_p1) + $signed(sext_ln813_1_fu_829_p1));

assign ret_V_2_fu_842_p2 = ($signed(ret_V_1_fu_832_p2) + $signed(sext_ln1347_fu_838_p1));

assign rhs_2_fu_817_p4 = {{grp_fu_1137_p2[29:16]}};

assign second_order_float_sin_cos_K0_V_address0 = zext_ln541_fu_761_p1;

assign second_order_float_sin_cos_K1_V_address0 = zext_ln541_fu_761_p1;

assign second_order_float_sin_cos_K2_V_address0 = zext_ln541_fu_761_p1;

assign select_ln1019_1_fu_1040_p3 = ((and_ln1019_reg_1186_pp0_iter16_reg[0:0] == 1'b1) ? select_ln288_fu_1033_p3 : out_exp_V_fu_1025_p3);

assign select_ln1019_fu_662_p3 = ((and_ln1019_reg_1186_pp0_iter6_reg[0:0] == 1'b1) ? results_sign_V_2_fu_657_p2 : results_sign_V_fu_649_p3);

assign select_ln1513_fu_720_p3 = ((isNeg_reg_1231[0:0] == 1'b1) ? lshr_ln1488_fu_708_p2 : shl_ln1454_fu_714_p2);

assign select_ln288_fu_1033_p3 = ((do_cos_read_reg_1144_pp0_iter16_reg[0:0] == 1'b1) ? 8'd127 : 8'd0);

assign select_ln300_1_fu_1099_p3 = ((icmp_ln300_2_reg_1253_pp0_iter17_reg[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln321_fu_1085_p3 = ((icmp_ln321_reg_1358[0:0] == 1'b1) ? tmp_8_fu_1066_p4 : tmp_9_fu_1076_p4);

assign select_ln482_fu_387_p3 = ((closepath_reg_1164_pp0_iter6_reg[0:0] == 1'b1) ? Ex_V_fu_382_p2 : 8'd0);

assign sext_ln1198_fu_466_p1 = $signed(p_Result_23_fu_458_p3);

assign sext_ln1347_fu_838_p1 = $signed(rhs_2_fu_817_p4);

assign sext_ln1512_fu_701_p1 = $signed(ush_fu_694_p3);

assign sext_ln1535_fu_685_p1 = Ex_V_3_reg_1225;

assign sext_ln186_fu_903_p1 = $signed(Ex_V_4_fu_897_p3);

assign sext_ln329_fu_992_p1 = $signed(add_ln329_fu_986_p2);

assign sext_ln813_1_fu_829_p1 = $signed(rhs_1_reg_1311_pp0_iter13_reg);

assign sext_ln813_fu_826_p1 = $signed(t1_V_reg_1296_pp0_iter13_reg);

assign shift_1_fu_978_p3 = ((icmp_ln321_fu_966_p2[0:0] == 1'b1) ? add_ln319_fu_972_p2 : c_fu_931_p3);

assign shl_ln1454_1_fu_960_p2 = zext_ln1488_1_fu_957_p1 << c_fu_931_p3;

assign shl_ln1454_2_fu_1061_p2 = zext_ln1488_2_fu_1057_p1 << c_2_reg_1347;

assign shl_ln1454_fu_714_p2 = zext_ln1488_fu_705_p1 << sext_ln1512_fu_701_p1;

assign significand_fu_1092_p3 = ((or_ln335_reg_1363[0:0] == 1'b1) ? 23'd0 : select_ln321_fu_1085_p3);

assign sin_basis_fu_560_p2 = (xor_ln25_fu_555_p2 ^ tmp_s_fu_520_p10);

assign sub_ln1512_fu_688_p2 = ($signed(9'd0) - $signed(sext_ln1535_fu_685_p1));

assign tmp_10_fu_1002_p3 = newexp_fu_996_p2[32'd31];

assign tmp_2_fu_430_p4 = {{Mx_bits_V_3_fu_423_p3[57:29]}};

assign tmp_8_fu_1066_p4 = {{shl_ln1454_2_fu_1061_p2[27:5]}};

assign tmp_9_fu_1076_p4 = {{shl_ln1454_1_reg_1352[27:5]}};

assign tmp_fu_394_p3 = ret_V_reg_1203[32'd77];

assign trunc_ln214_fu_1021_p1 = newexp_fu_996_p2[7:0];

assign trunc_ln628_fu_305_p1 = addr_fu_282_p3[3:0];

assign ush_fu_694_p3 = ((isNeg_reg_1231[0:0] == 1'b1) ? sub_ln1512_fu_688_p2 : sext_ln1535_fu_685_p1);


always @ (sext_ln1198_fu_466_p1) begin
    if (sext_ln1198_fu_466_p1[0] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd0;
    end else if (sext_ln1198_fu_466_p1[1] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd1;
    end else if (sext_ln1198_fu_466_p1[2] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd2;
    end else if (sext_ln1198_fu_466_p1[3] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd3;
    end else if (sext_ln1198_fu_466_p1[4] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd4;
    end else if (sext_ln1198_fu_466_p1[5] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd5;
    end else if (sext_ln1198_fu_466_p1[6] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd6;
    end else if (sext_ln1198_fu_466_p1[7] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd7;
    end else if (sext_ln1198_fu_466_p1[8] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd8;
    end else if (sext_ln1198_fu_466_p1[9] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd9;
    end else if (sext_ln1198_fu_466_p1[10] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd10;
    end else if (sext_ln1198_fu_466_p1[11] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd11;
    end else if (sext_ln1198_fu_466_p1[12] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd12;
    end else if (sext_ln1198_fu_466_p1[13] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd13;
    end else if (sext_ln1198_fu_466_p1[14] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd14;
    end else if (sext_ln1198_fu_466_p1[15] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd15;
    end else if (sext_ln1198_fu_466_p1[16] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd16;
    end else if (sext_ln1198_fu_466_p1[17] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd17;
    end else if (sext_ln1198_fu_466_p1[18] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd18;
    end else if (sext_ln1198_fu_466_p1[19] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd19;
    end else if (sext_ln1198_fu_466_p1[20] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd20;
    end else if (sext_ln1198_fu_466_p1[21] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd21;
    end else if (sext_ln1198_fu_466_p1[22] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd22;
    end else if (sext_ln1198_fu_466_p1[23] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd23;
    end else if (sext_ln1198_fu_466_p1[24] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd24;
    end else if (sext_ln1198_fu_466_p1[25] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd25;
    end else if (sext_ln1198_fu_466_p1[26] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd26;
    end else if (sext_ln1198_fu_466_p1[27] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd27;
    end else if (sext_ln1198_fu_466_p1[28] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd28;
    end else if (sext_ln1198_fu_466_p1[29] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd29;
    end else if (sext_ln1198_fu_466_p1[30] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd30;
    end else if (sext_ln1198_fu_466_p1[31] == 1'b1) begin
        val_assign_fu_470_p3 = 32'd31;
    end else begin
        val_assign_fu_470_p3 = 32'd32;
    end
end

assign xor_ln1027_fu_407_p2 = (closepath_reg_1164_pp0_iter6_reg ^ 1'd1);

assign xor_ln25_fu_555_p2 = (do_cos_read_reg_1144_pp0_iter6_reg ^ 1'd1);

assign xor_ln271_fu_542_p2 = (tmp_s_fu_520_p10 ^ 1'd1);

assign zext_ln1271_fu_751_p1 = B_trunc_fu_741_p4;

assign zext_ln1454_fu_486_p1 = Mx_zeros_fu_478_p1;

assign zext_ln1488_1_fu_957_p1 = result_V_reg_1331;

assign zext_ln1488_2_fu_1057_p1 = r_V_11_fu_1054_p1;

assign zext_ln1488_fu_705_p1 = Mx_V_reg_1219;

assign zext_ln541_1_fu_300_p1 = r_V_fu_290_p4;

assign zext_ln541_fu_761_p1 = p_Result_24_fu_755_p3;

assign zext_ln841_fu_482_p1 = Mx_zeros_fu_478_p1;

assign zext_ln930_fu_327_p1 = trunc_ln628_reg_1181;

endmodule //freq_translator_sin_or_cos_float_s
